### ISSUE TITLE
One question about the TAP interface "ap"

### ISSUE THREAD

**Issue by josemariasaldana** [fgg89/odin#2]
Hi, Francisco.

I am trying to run Odin. I have been able to run almost everything. I can even connect at WiFi level a Station with Odin. But my agent losses the ARP requests. They dissappear as soon as they are sent to the host, using the Click function "ToHost".

They appear in "ap" (I can see them with tcpdump), but it seems that Linux drops them. Do I have to do something with "ap"? Does it require an IP address?

Thanks in advance!

**Comment by benboy-han** [comment]
Hi josemariasaldana.
Can you share me with the webpage about  Francisco! I need to more help !Thanks in advance

**Comment by fgg89** [comment]
Hi @josemariasaldana,

I am not sure about the reason why the ARP messages are dropped, are you using the agent-generator script for creating the agent.click file? are you able to complete the DHCP negotiation?

Nothing additional is required in the ap interface and it also does not need an IP address.

Regards,
Francisco

**Comment by josemariasaldana** [comment]
Hi, Francisco. Thanks a lot.

We are using the agent generator script. We are able to create an ESSID using Odin, and to connect it at WiFi level.

However, when the ARPs arrive at Click, and it makes a "ToHost(ap)", they arrive nowhere. The TAP interface 'ap' does exist, but the ARPs do not arrive to the kernel.

We are doing theses things with openvswitch:

$: /etc/init.d/openvswitch start

Add a bridge named br0:
$: ovs-vsctl add-br br0

Connect the bridge to an Openflow controller:
$: ovs-vsctl set-controller br0 tcp:155.210.157.237

Add a datapath named dp0:
$: ovs-dpctl add-dp dp0

Add the ap device to dp0 OpenvSwitch datapath (after Click is started):
$: ovs-dpctl add-if dp0 ap

Everything seems to work, but nobody answers the ARPs.

Thanks in advance!

**Comment by josemariasaldana** [comment]
Another question which I am perhaps leaving apart:

I have installed openvswitch, but I have not modified all the configuration files (as https://gist.github.com/marciolm/9f0ab13b877372d08e8f). Is this also necessary?

Thanks,

Jose

**Comment by benboy-han** [comment]
Hi josemariasaldana ,
  https://gist.github.com/marciolm/9f0ab13b877372d08e8f. This website can not be open.Is there some wrong?

**Comment by josemariasaldana** [comment]
It works for me. Look in https://gist.github.com/marciolm,  <https://gist.github.com/marciolm/9f0ab13b877372d08e8f> S99bootovs
 
Jose
 
De: benboy-han [mailto:notifications@github.com] 
Enviado el: jueves, 28 de mayo de 2015 13:20
Para: fgg89/odin
CC: Jose Saldana
Asunto: Re: [odin] One question about the TAP interface "ap" (#2)
 
Hi josemariasaldana ,
https://gist.github.com/marciolm/9f0ab13b877372d08e8f. This website can not be open.Is there some wrong?

**Comment by fgg89** [comment]
Hi @josemariasaldana 

Regarding OVS configuration, I am not so experienced with the vswitch since I used xDPd for setting up the Odin project. However your steps look good, ap and dp0 should be ports of the switch and I do not think that extra configuration should be needed.

Regarding the ARP packets, maybe it is a problem of OVS not knowing what to do with them?

P.S: Are you using static IP addresses via the clientList file or do you get the IP via DHCP?

**Comment by benboy-han** [comment]
Hi, Francisco.
            I have place a clientlist file in the OdinMaster, and when the controller startup, the file was read, but my client can't connect to the odin network thought the signal can be found.my network topolopy is follow:
I use a wireless router as a openflow switch which runs openvswitch, and other wireless routers as two AP which close the DHCP function, they run the odin-agent. The way of connection of them is that:the two AP's lan port connect to the switch'lan port.My network don't connect to the public network. And the controller connect to the switch is my laptop which runs the Master.Are there some wrongs with my topolopy?

**Comment by benboy-han** [comment]
Hi, @fgg89 Francisco.
I have place a clientlist file in the OdinMaster, and when the controller startup, the file was read, but my client can't connect to the odin network thought the signal can be found.my network topolopy is follow:
I use a wireless router as a openflow switch which runs openvswitch, and other wireless routers as two AP which close the DHCP function, they run the odin-agent. The way of connection of them is that:the two AP's lan port connect to the switch'lan port.My network don't connect to the public network. And the controller connect to the switch is my laptop which runs the Master.Are there some wrongs with my topolopy?

**Comment by benboy-han** [comment]
Hi, @josemariasaldana
 I recompile the firmware,but i met a problem, the LINK click procedure is failed. my error is that:

/../../trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld：odinagent.o:.text+0x260:Unsupported jump between ISA modes; consider recompiling with interlinking enabled.
/../../trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld：final link failed:Bad value.

my router is mw4530R.Did you meet this quesion?can you give me some suggestion?Thanks in advance

**Comment by josemariasaldana** [comment]
Hi,

I have no experience with that. I am not an expert on cross-compiling. I have only found this:
http://ww1.microchip.com/downloads/en/DeviceDoc/xc32-v1.34-release-notes.html:

MPORTANT: Standard function calls can switch between MIPS32 and microMIPS modes. However, when calling a MIPS32 library function from a microMIPS function, the compiler may generate a compressed jals instruction to call the library function. A jals instruction cannot change modes to MIPS32 and upon linking, you may receive an error, "Unsupported jump between ISA modes; consider recompiling with interlinking enabled." In that case, add the -mno-jals option to the Alternate Options field in your project properties for xc32-gcc so that it is passed to the compiler.

**Comment by josemariasaldana** [comment]
Hi, @fgg89 Francisco.

Thank you very much for your response. We have been able to make Odin run here. ¡Muchas gracias!

José Mª

**Comment by fgg89** [comment]
@josemariasaldana you're welcome, I am glad to see you got it working! :) May I know what was the issue? It could help other users (and also me, since it has been a long time that I don't test this project) to setup a new Odin testbed.

@benboy-han, regarding your topology I would try to have the most simple scenario possible, e.g. only one access point, test connectivity with the master/controller, make sure the switch acts as it should (with the learning switch functionality your device should get an IP via DHCP and you wouldn't need to use the clientName file) and then make sure you're able to connect a client device.   

Regards,
Francisco

**Comment by josemariasaldana** [comment]
Hi, @fgg89, there were two problems:

- We were not doing "ifconfig ap up" after initiating Click, and it seems to be necessary.

- We were not adding the network interfaces to the same openflow bridge.

Thanks a lot!

**Comment by fgg89** [comment]
Hi @josemariasaldana ,

I wasn't sure if you had a look to the setup-odin script, I tried to set there everything that should happen before odin runs, such as bringing the interfaces up and making the process as automatic as possible. However there's a lot of room for improvement...

Thanks for the feedback! ;-)

**Comment by mhby** [comment]
hi @josemariasaldana 
I built the 'click' in the openwrt environment. when I tried to  pass the '--enable-local' flag to Click's configure script to build the click, I meet the same errors as benboy-han. I have read your advices, but I do not understand the meaning. could you tell me how to fix it ?  "In that case, add the -mno-jals option to the Alternate Options field in your project properties for xc32-gcc so that it is passed to the compiler." how should I add the "-mno-jals" in my environment?

**Comment by josemariasaldana** [comment]
Hi, @mhby and @benboy-han. This is a summary of what we did for cross-compiling Click with Odin ("proyecto" is the username in our Linux machine):

Prepare the toolchain and SDK in the host machine
We downloaded the sources from the OpenWRT git:
root@proyecto:/home/proyecto/openwrt# git clone git://git.openwrt.org/14.07/openwrt.git trunk

and compiled them. As a result, this machine has a complete OpenWRT toolchain and SDK including the sources in the directory /home/proyecto/openwrt/trunk/

In the host machine, prepare the variables for cross-compiling:
Modify the CC variable in order to make the compiler be the MIPS one:
export CC=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc

Modify CXX:
export CXX=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-g++

Add this to the path:
export PATH=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/:$PATH

Modify the STAGING_DIR variable:
export STAGING_DIR=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/

Use $set to see the values of the variables.

In the host machine, download and compile Click:
Download Click router source code to the directory:
# cd /home/proyecto/openwrt/trunk/click

# git clone git://github.com/kohler/click.git

If you want to add some features to click (e.g. odin agent), you should add them now to /home/proyecto/click/elements/local/

Run make clean if you want to rebuild:
root@proyecto:/home/proyecto/openwrt/trunk/click# make clean

If you are installing Odin, the two odin files (cc and hh) will be in openwrt/trunk/click/elements/local. You will also need --enable-local, --enable-userlevel and --enable-wifi, so use:

root@proyecto:/home/proyecto/openwrt/trunk/click# ./configure --disable-app-fuzzer --disable-app-performance --disable-app-sniffer --enable-app-tunnel --disable-app-stats --disable-doc --disable-doc-man --enable-local --enable-userlevel --enable-wifi  --host=mips-unknown-elf --build=mips --prefix=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/ --with-linux=/home/proyecto/openwrt/trunk/build_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/linux/


Run make
root@proyecto:/home/proyecto/openwrt/trunk/click# make

**Comment by josemariasaldana** [comment]
Hi, @fgg89 , I have another question: Which interfaces of the AP have to be controlled by Openflow?

The AP (TP-LINK 1043 running OpenWRT) has the next interfaces:
- mon0 (mobile communications)
- 4 internal ports (yellow): ethx
- 1 WAN port (blue): eth
- TAP interface 'ap' created by Click.

Which ones have to be added to the openflow switch br0?

Is it enough if we add the 'ap' interface?

What is the best place for the DHCP server? Each AP? An external machine connected to the internal network?

Thanks!

**Comment by fgg89** [comment]
Hi @josemariasaldana,

In my setup I had both the "ap" and my wan interface (your "eth") connected to the switch.

The agent.click contains the click config for WiFi encap/decap, deal with ARP and send to the mon0 interface (among other minor things)...you shouldn't do anything else with this interface (just remember to increase the MTU of the mon0 to handle WiFi packets properly since the MTU is larger than in Ethernet: ifconfig mon0 mtu 2200).

Regarding the DHCP server, I had an internal machine in the network for that, so the AP didn't have to deal with the requests, just forward them. I cannot say what is better but either way you should probably know that there's a flow set in the original OdinAgent class (inside the master in the Floodlight controller) which filters DHCP offers to let the OdinMaster know about the IP of the client (for internal purposes), then the offer gets to the ap interface and it is sent to the mon0.

Regards,
Fran

**Comment by benboy-han** [comment]
Hi @josemariasaldana,
In your setup, the openvswitch ——bro is used to connect with the master, and in the openwrt of AP, there is a br-lan which is used to bridge wlan0 and eth0. so did your br0 replace the br-lan? or they are  coexit?Thanks in advance.
Regards,
benboy

**Comment by josemariasaldana** [comment]
The br0 replaces the br-lan.

**Comment by benboy-han** [comment]
Hi @josemariasaldana,
 Thank you for your help! you have successed to run Odin,Congratulations! last time , i told you that my client can not connect to SSID which was created my master. and i have tried many times, but the problem can not be resolved.I am not sure whether my setup is wrong or my network topolopy of expriment is wrong.So ,can you share me some more detailed setup and network topolopy about your expriment, so that I can get some reference from you?I am upset about this problem.Thanks in advance.
Regards,
benboy

**Comment by josemariasaldana** [comment]
Hi,

I have improved the instructions in github. See https://github.com/Wi5/odin

In addition, I have put my setup here https://github.com/Wi5/odin/blob/master/Scenario_odin_working-jun-2015.pdf .

I have two different machines: one is the odin controller and another one is the DHCP server. In addition, 192.168.1.5 is the AP that creates the odin ESSID.

All the machines are connected by means of another network, using different directions.

BR,

Jose

**Comment by benboy-han** [comment]
Hi, @fgg89 ,Did you have successed to run Odin? And in your setup, how to configure the openvswitch? Can you share me with your idea?Thanks in advance.
Regards,
benboy

**Comment by benboy-han** [comment]
Hi @josemariasaldana,
   Today, i  have tried  to capture the packets of the process of wifi connection. the result was that: client send the probe request and got the probe response from the Odin system with the unique BSSID. For example, the MAC of the client is 50:a4:c8:d3:73:73, so the BSSID in the probe response is  00:1b:b3:d3:73:73 which is match with the way of generating the BSSID in the source code of master.But  i can not capture the packets of Authentication and Association . So ,i think this is the reason why my client can not connect to the odin-network.What your idea? And can you give me some good suggestion so that i can resolve the problem. I am trying to settle the problem.Thanks in advance.

BR,
benboy

**Comment by fgg89** [comment]
Hi @benboy-han 

It's been half a year since I tested odin, I used the soft switch xDPd instead of OVS and back then it worked. However now I'm having issues trying to make it run either with xDPd or with OVS. I cannot get DHCP offers to the monitor interface. 

I had a quick test configuring OVS like this (not sure if it's enough though):

ovs-vsctl add-br br0
ovs-vsctl set-controller br0 tcp:192.168.1.24:6633
ovs-vsctl add-port br0 ap
ovs-vsctl add-port br0 eth0

Regards,
Francisco

**Comment by haizeiwang507** [comment]
> Hi,@josemariasaldana. 
I built the 'click' in the openwrt environment，and i have done like you said.

This is a summary of what we did for cross-compiling Click with Odin ("proyecto" is the username in our Linux machine):
> 
> Prepare the toolchain and SDK in the host machine
> We downloaded the sources from the OpenWRT git:
> root@proyecto:/home/proyecto/openwrt# git clone git://git.openwrt.org/14.07/openwrt.git trunk
> 
> and compiled them. As a result, this machine has a complete OpenWRT toolchain and SDK including the sources in the directory /home/proyecto/openwrt/trunk/
> 
> In the host machine, prepare the variables for cross-compiling:
> Modify the CC variable in order to make the compiler be the MIPS one:
> export CC=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc
> 
> Modify CXX:
> export CXX=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-g++
> 
> Add this to the path:
> export PATH=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/:$PATH
> 
> Modify the STAGING_DIR variable:
> export STAGING_DIR=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/
> 
> Use $set to see the values of the variables.
> 
> In the host machine, download and compile Click:
> Download Click router source code to the directory:
> 
> cd /home/proyecto/openwrt/trunk/click
> 
> git clone git://github.com/kohler/click.git
> 
> If you want to add some features to click (e.g. odin agent), you should add them now to /home/proyecto/click/elements/local/
> 
> Run make clean if you want to rebuild:
> root@proyecto:/home/proyecto/openwrt/trunk/click# make clean
> 
> If you are installing Odin, the two odin files (cc and hh) will be in openwrt/trunk/click/elements/local. You will also need --enable-local, --enable-userlevel and --enable-wifi, so use:
> 
> root@proyecto:/home/proyecto/openwrt/trunk/click# ./configure --disable-app-fuzzer --disable-app-performance --disable-app-sniffer --enable-app-tunnel --disable-app-stats --disable-doc --disable-doc-man --enable-local --enable-userlevel --enable-wifi --host=mips-unknown-elf --build=mips --prefix=/home/proyecto/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/ --with-linux=/home/proyecto/openwrt/trunk/build_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/linux/
> 



now , I get a problem as flow:

 LINK click-mkmindriver
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
/home/sdn/zei/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: ../lib/libclicktool_build.a(string.bo): Relocations in generic ELF (EM: 3)
../lib/libclicktool_build.a: could not read symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[6]: *** [click-mkmindriver] Error 1
make[6]: Leaving directory `/home/sdn/zei/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/click-2.0.1/tools/click-mkmindriver'
make[5]: *** [install-subdirs] Error 1
make[5]: Leaving directory `/home/sdn/zei/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/click-2.0.1/tools'
make[4]: *** [install-tools] Error 2
make[4]: Leaving directory `/home/sdn/zei/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/click-2.0.1'
make[3]: *** [/home/sdn/zei/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/click-2.0.1/.built] Error 2
make[3]: Leaving directory `/home/sdn/zei/trunk/package/feeds/packages/click'
make[2]: *** [package/feeds/packages/click/compile] Error 2
make[2]: Leaving directory `/home/sdn/zei/trunk'
make[1]: *** [/home/sdn/zei/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/sdn/zei/trunk'


I have tried all methods from Google(make clean the old compile environment or change the path) ,but can't slove it .can you help me ?thank you !




I had made the command as flow:
sdn@sdn:~/wang/trunk$
 export PATH=$PATH:/home/sdn/wang/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/
sdn@sdn:~/wang/trunk$ 
export CC=/home/sdn/wang/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc
sdn@sdn:~/wang/trunk$ 
export CXX=/home/sdn/wang/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-g++
sdn@sdn:~/wang/trunk$
 export STAGING_DIR=/home/sdn/wang/trunk/staging_dir/

./configure --enable-local --enable-userlevel --enable-wifi --host=arm-linux --build=mips --prefix=/home/sdn/wang/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/
 --with-linux=/home/sdn/wang/trunk/build_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/linux/

**Comment by josemariasaldana** [comment]
Hi,

I must say I also obtain an error stating that click-mkmindriver could not be compiled.

However, it is not important since this application is not necessary to run Click: “the click-mkmindriver tool generates a build environment for a minimal Click driver -- that is, a driver containing only the elements necessary to run the configurations in the router-files” (http://www.read.cs.ucla.edu/click/docs/click-mkmindriver). 

So I took the generated "click" file (generated in /click/userlevel), and it runs correctly.

**Comment by haizeiwang507** [comment]
HI,@josemariasaldana
 I have removed the click-mkmindriver ,then it compile successful(in click/userlevel).and it run correctly,run the odin system successfully, but my mobile phone can't connect to this wifi ( my phone can recognised the wifi signal:open_mobility_network ,and I have put the phone MAC into odin_client_list.)
I don't know the reason, Is there something to be changing?can you help me ,thank you very much !

**Comment by josemariasaldana** [comment]
Hi,
 
Have you patched the ath9k driver? You can use Wireshark in order to see which frames appear.
 
You can also use these scripts to start Odin: https://github.com/Wi5/odin-agent/tree/master/scripts_start_ap_odin
 
Sorry for the delay.
 
Jose 
 
De: haizeiwang507 [mailto:notifications@github.com] 
Enviado el: martes, 08 de septiembre de 2015 4:37
Para: fgg89/odin <odin@noreply.github.com>
CC: Jose Saldana <jsaldana@unizar.es>
Asunto: Re: [odin] One question about the TAP interface "ap" (#2)
 
HI,@josemariasaldana <https://github.com/josemariasaldana> 
I have removed the click-mkmindriver ,then it compile successful(in click/userlevel).and it run correctly,run the odin system successfully, but my mobile phone can't connect to this wifi ( my phone can recognised the wifi signal:open_mobility_network ,and I have put the phone MAC into odin_client_list.)
I don't know the reason, Is there something to be changing?can you help me ,thank you very much !

**Comment by leite1992** [comment]
HI, @josemariasaldana 
    Rcently,I am ready to use the platform of Odin.But I don't know use what I use Router model. so , I want to know the Router model, it is used to develop the system of Odin by your team. can you tell me..Thanks. Best wishes for you.

**Comment by josemariasaldana** [comment]
We are using TP-Link 1043ND (version2): http://wiki.openwrt.org/toh/tp-link/tl-wr1043nd

**Comment by leite1992** [comment]
HI, @josemariasaldana 
I have finished compiling the Odin. But,the mobile phone can't obtain the IP address when I run the Odin on the router. What reasons may result in the condition? Is it the process of DHCP is error?

**Comment by leite1992** [comment]
HI, @josemariasaldana 
Can U help me. Thanks...

**Comment by josemariasaldana** [comment]
You can do the next things:

1. Check if Odin works without DHCP. Have a look to https://github.com/Wi5/odin/blob/master/README.md, and do the things without DHCP (Odin client list (only required when DHCP is not used))

Then, you will know if the problem is related to DHCP or not. I mean, if you are able to connect when no using DHCP, it means that the problem is DHCP.

2. Create a DHCP server (it can be in the same machine where the Odin controller is), and disable the DHCP server of the Access Point. Use Wireshark and look for the DHCP messages. Check if the mobile is sending it, if the controller is answering, etc.

**Comment by leite1992** [comment]
Hello! @josemariasaldana 
I have saw the URL. I want to know the how Controller control the ap to do command(eg: ADD_LVAP,REMOVE_LVAP,QUERY_STATS,ADD_SUBSCRIPTION),why the Controller do the command.For example , The Controller do ADD_LVAP when the STA send the PROBE_REQUEST.
Can U tell me. Thank your answers.Best wishes for U.

**Comment by leite1992** [comment]
@josemariasaldana 
I use tcpdump catch the data of Mon0 Interface. I find the probe_brocast,probe_request,beacon frame and probe_response .But can't find Authenticate and 
Associate.what is the process of mobile phone connect the AP in the Odin?

**Comment by haizeiwang507** [comment]
Hi,@josemariasaldana
My Router is  NETGEAR WNDR3700V2, It exits two physical network cards (one for lan,one for wlan), May  I should make some changes in odinagent.cc and odinagent.hh ?where and why ? can you give me some suggestions ?thank you !

**Comment by josemariasaldana** [comment]
I don't think you nave to modify odinagent.cc. you only have to specify your router (in the Make Menuconfig) when you are compiling OpenWRT.

**Comment by leite1992** [comment]
Hi,@josemariasaldana 
The  flash of TP-Link 1043ND(v2) is 8MB. can it run the firmware? Is 8MB flash enough?Do you add the flash to 16MB? Can the latest system of Odin run in the 8MB flash? Can you  give me the bin flies of the TP-Link 1043ND.

**Comment by josemariasaldana** [comment]
What we are doing now is compiling OpenWRT (without Click) for the TP-Link1043ND router. We flash it in the router. Then, we cross-compile Click and copy it to a USB drive connected to the TP-Link. We run Click from the USB. 

The .bin is here: https://dl.dropboxusercontent.com/u/67016195/openwrt-ar71xx-generic-tl-wr1043nd-v2-squashfs-sysupgrade.bin

The click file is here: https://dl.dropboxusercontent.com/u/67016195/click

The click-align file is here: https://dl.dropboxusercontent.com/u/67016195/click-align

Best regards.

**Comment by haizeiwang507** [comment]
Hi,@josemariasaldana 
I have get one TP-Link1043ND router. but I can't open : https://dl.dropboxusercontent.com/u/67016195/openwrt-ar71xx-generic-tl-wr1043nd-v2-squashfs-sysupgrade.bin...(without VPN)  ,,,Can you send your '.bin' file to me?（compiled OpenWRT (with Click and odinagent.cc odinagent.hh inside ) for the TP-Link1043ND router）(my email is  984185860@qq.com )  ... the netgear wndr3700V2 router is hard to succeed (the WLAN device is different with TP-Link1043ND router ),   best wishes to you ! thank you!

**Comment by josemariasaldana** [comment]
I have just sent them to you.

**Comment by haizeiwang507** [comment]
Hi,@josemariasaldana   
Thank you very much! maybe there some problems,I have not received your 'bin' file,Can you send it to me again with E-mail attachments(  jiaoleite@126.com  or  984185860@qq.com   both okay) ,thank you !

**Comment by haizeiwang507** [comment]
Hi,@josemariasaldana
I have got it ,thanks!God bless U!

**Comment by leite1992** [comment]
Hi,@josemariasaldana
 I have run the Odin in the tplink 1043nd.I want to add some functions such like the Web Authentication at now.Would you give some suggestions for me. Thank you. Best wishes for you.

**Comment by haizeiwang507** [comment]
Hi,@josemariasaldana
I have read some articles about wireless driver of atheros , maybe just like you say , there are some problems  in network surpport (about wireless)  when  make menuconfig /make kernel_menuconfig  to compile openwrt .  ...    .that is method in article:

Enabling ath9k
To enable ath9k, you must first enable mac80211 through make menuconfig when compiling your kernel. If you do not know what this means then please learn to compile kernels or rely on your Linux distribution's kernel. Below are the options you need to enable ath9k through make menuconfig.

Networking  --->
  Wireless  --->
    <M> Improved wireless configuration API
    <M> Generic IEEE 802.11 Networking Stack (mac80211)
You can then enable ath9k in the kernel configuration under
Device Drivers  --->
  [*] Network device support  --->
        Wireless LAN  --->
          Atheros Wireless Cards ---->
            <M>   Atheros 802.11n wireless cards support

but I find none of them in my openwrt ,can you help me ?how do you select in network surport about wireless part (both make menuconfig and make kernel_menuconfig ) ,,, (my trunk version is 3.10.36 and ubuntu is  3.11.0-15-generic)

**Comment by josemariasaldana** [comment]
HI,

I have not selected the ath9k directly. I just selected my AP: TP-Link 1043ND, and I think this implies that you are selecting the required driver (ath9k in this case).

**Comment by haizeiwang507** [comment]
Hi,@josemariasaldana
yes ,I just want to try to  select ath9k,but I can't find these options.. Can you show me your network config ?(I just want to see what options have to be selected about wireless in your openwrt , maybe the default is different)  ...  ......   ....Today , I have got my  TP-Link 1043ND router ,then I put the 'bin 'file （you give me ）in it  successfully, but I find there is no click .. I'm sorry to trouble you again, Can you give me the click*.ipk(compile with  TP-Link 1043ND) or the 'bin'file with into click part ,my email is  jiaoleite@126.com ,,,Thank you !

**Comment by haizeiwang507** [comment]
Hi,@josemariasaldana
I don't how use in usb  ,,I put click and click-align in u disk  (usb) 。。。 but click don't work .. can you tell me how to use ? thank you !

**Comment by fgg89** [comment]
Hi all,

The issues are meant to solve particular problems for the project, rather than being a sort of forum. It is for this reason that I will consider this issue as closed. Please take this into account for the future.

Thank you.

Regards,
fgg89
